Java treeview
MobSF/Mobile-Security-Framework-MobSF pull request #1364
Opened 2020-04-18 19:56 UTC by matandobr

! ONGOING PR !

- Tested on Windows til now
- Changed the Java view to the tree-view
- Used jsTree library for the javascript tree-view (@ajinabraham - do we need to add their license?)
- The whole data is generated within the HTML with a os.dir + template generator hack, big thanks to Elf Sternberg from [this thread ](https://stackoverflow.com/questions/6297068/whats-the-django-way-to-render-a-tree-of-folders-and-files)
- For now the filename filtering is done in the client side, and the content search is done both in the client and server side (Query the find source view for all the files that match the query -> get all of the files and only "higlight" them in the client side - actually I search the whole paths with a hack in the client side, refer to the new search callback for the implementation...)

2020-04-22 20:12 UTC, matandobr commented on StaticAnalyzer/views/android/java.py
> +            if os.path.isdir(t):
I didn't get why should we argue with the python cross platform solution with something that is simple as directory checking..  isn't is complicating a simple thing?

2020-04-22 20:19 UTC, ajinabraham commented on StaticAnalyzer/views/android/java.py
> +            if os.path.isdir(t):
So reason for this is that I was thinking it's nice to replace os.path with the new pathlib
https://docs.python.org/3/library/pathlib.html If we stick with a function from utils, it is so easy to maintain and update this.

2020-04-22 20:23 UTC, matandobr commented on StaticAnalyzer/views/android/java.py
> +            if os.path.isdir(t):
Got you,
I'll stick with the projects standard of course.

2020-08-06 18:09 UTC, ajinabraham commented
@matandobr Got a chance to look into the review comments?

2020-08-11 17:44 UTC, matandobr commented
Hey @ajin sorry for the late reply.
I'll try to finish this weekend.

2020-09-20 11:40 UTC, matandobr commented
Tested on Ubuntu 18 
![image](https://user-images.githubusercontent.com/6709304/93710334-7ceab980-fb4e-11ea-94df-1b5b1e9c4499.png)

2020-09-26 14:28 UTC, matandobr commented
@ajinabraham @superpoussin22 
Hey, Ready for review and testing :)

2020-09-26 16:55 UTC, ajinabraham commented
Gonna take a dig!

2020-09-26 17:06 UTC, matandobr commented
@ajinabraham 
Also, a thought - does it makes sense to add a package / app name in the title? 
Like 
Java source - a.b.c v4.3.2

2020-09-26 17:07 UTC, ajinabraham commented
Yes it does

2020-09-26 18:15 UTC, ajinabraham commented
@matandobr I am still getting crashed/slow browser for a pretty large APK like Spotify on a couple of file name search. 
Tested on Chrome and Firefox.

<img width="483" alt="Screenshot 2020-09-26 at 2 03 49 PM" src="https://user-images.githubusercontent.com/4301109/94347336-3fc87080-0001-11eb-9198-68b20f445b3c.png">

Can search filename only on enter key improve this behavior?

And for file content search inside a large APK source. It's incredibly slow compared to server-side searching. Can we move this logic to server side AJAX calls to speed that up? It's either browser restrict CPU/RAM to tabs or client side JavaScript can't do this heavy lifting due to browser imposed restrictions or we have leaks somewhere.

I really like this single page UI especially the searching part and awesome UX, but we need to be stable and consistent across large/small files.
https://streamable.com/0sqzqp
On Macbook pro, Core i7 2.7GHz, 16GB RAM

2020-09-27 05:39 UTC, matandobr commented
> @matandobr I am still getting crashed/slow browser for a pretty large APK like Spotify on a couple of file name search.
> Tested on Chrome and Firefox.
> 
> <img alt="Screenshot 2020-09-26 at 2 03 49 PM" width="483" src="https://user-images.githubusercontent.com/4301109/94347336-3fc87080-0001-11eb-9198-68b20f445b3c.png">
> 
> Can search filename only on enter key improve this behavior?
> 
> And for file content search inside a large APK source. It's incredibly slow compared to server-side searching. Can we move this logic to server side AJAX calls to speed that up? It's either browser restrict CPU/RAM to tabs or client side JavaScript can't do this heavy lifting due to browser imposed restrictions or we have leaks somewhere.
> 
> I really like this single page UI especially the searching part and awesome UX, but we need to be stable and consistent across large/small files.
> https://streamable.com/0sqzqp
> On Macbook pro, Core i7 2.7GHz, 16GB RAM

@ajinabraham , Are you actually experiencing a "crush"? - the video you sent is just loading, maybe it will actually appear after some time, also you searched for an extremely common word in the content search,
I 'm not able to see the picture you uploaded, could you send me on slack?

2020-09-27 16:18 UTC, ajinabraham commented
@matandobr The page becomes unresponsive and the browser interferes after being unresponsive after a while. The results might appear after prolonged waiting, but that is quite a performance impact. The server-side implementation of the same is much faster. Can we change the logic to use server-side search?

2020-09-29 15:58 UTC, matandobr commented
@ajinabraham 
I'll try to change the filename search to server-side.
Besides that, the content just really takes a lot of time, also in the python side. 
I looked at find.py and I think we could make this more efficient - 
![image](https://user-images.githubusercontent.com/6709304/94583016-a067df80-0285-11eb-86b7-a8244a51d562.png)
I think reading the whole source files isn't the right way to go, If we are trying to search a text within those files I think reading line by line would be extremely more efficient.

2020-09-30 06:24 UTC, matandobr commented
@ajinabraham After some debugging, the thing that takes most of the time is the searching within the the JS side,
I found a way to overcome it, on it.

2020-09-30 16:25 UTC, matandobr commented
Changed the Filename to server side + JS side improvements

2020-10-07 18:21 UTC, matandobr commented
@ajinabraham Fixed all latest rejects, 
Works awesome now.

2020-10-08 01:54 UTC, ajinabraham requested changes
Android Source ZIP file view functions do not work, also kotlin support looks removed as per https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1364/files#diff-5e1eb72d457ddf6666cb55be6f61c9b7L42

2020-10-08 01:54 UTC, ajinabraham commented on StaticAnalyzer/views/android/find.py
> -        matches = set()
@matandobr This section added support for kotlin, and android zipped source code , both eclipse and android studio. This looks like removed in the PR

2020-10-13 17:41 UTC, ajinabraham reviewed
Code Looks Great @matandobr 
Testing this out.

2020-10-13 18:57 UTC, matandobr commented on StaticAnalyzer/views/android/find.py
> +        return JsonResponse(json.dumps(context), safe=False)
Inherited from previous code I guess? 
no particular reason..

2020-10-13 19:02 UTC, matandobr commented on StaticAnalyzer/views/android/find.py
> +        return JsonResponse(json.dumps(context), safe=False)
OK, I guess that this is the reason 
![image](https://user-images.githubusercontent.com/6709304/95904134-c28e5100-0d9f-11eb-8b2c-34c4f3f5455d.png)

2020-10-13 19:05 UTC, matandobr commented on StaticAnalyzer/views/android/find.py
> +        return JsonResponse(json.dumps(context), safe=False)
This is due the list inside the dict... there is no easy way to overcome it

2020-10-13 20:22 UTC, ajinabraham commented
@matandobr Both File and Content search does not return any results now.

2020-10-13 20:25 UTC, matandobr commented
> @matandobr Both File and Content search does not return any results now.

🤔 Any errors?

2020-10-13 20:29 UTC, ajinabraham commented
Something with the UI may be?

<img width="1388" alt="Screenshot 2020-10-13 at 4 29 06 PM" src="https://user-images.githubusercontent.com/4301109/95912780-47ae4180-0d71-11eb-88af-2615eaf1e4b3.png">

2020-10-18 20:44 UTC, ajinabraham commented
@matandobr Tried this up on a fresh instance. Still the same. I think the search is happening but the UI is not updated accordingly.
<img width="1435" alt="Screen Shot 2020-10-18 at 4 43 46 PM" src="https://user-images.githubusercontent.com/4301109/96385334-34c8b200-1161-11eb-9830-9bfae40a022d.png">

2020-10-19 16:53 UTC, matandobr commented
@ajinabraham 
Fixed the search issue in mac/linux

2020-10-24 19:30 UTC, ajinabraham commented
@matandobr I made some fixes to remove slash modifications which can be a pain in the ass across Windows/*nix.
Can you test it in windows? I don't have access to Windows until next month.
Also please remove this `replace()` if it is not relevant. https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1364/files#diff-fd455d570d21d6d55a8fbc8883076ffe2a712c26d7cab5c79f9f644342342f0cR105

2020-10-24 20:46 UTC, matandobr commented
Hey @ajinabraham thank you for the review, 
your modification for the sanitized slashes is exactly what I fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1364/commits/5540bd82ed779dd333221d155f51748b94a47154

So no it does not work now...
![image](https://user-images.githubusercontent.com/6709304/97093241-efb9e980-1652-11eb-8056-b92dd421a5f9.png)

2020-10-24 20:48 UTC, ajinabraham commented
@matandobr That fix had issues. The find was successful but the file read was failing in *nix.

2020-10-24 20:49 UTC, matandobr commented
@ajinabraham Are you sure? I tested it on linux 👍

2020-10-24 20:52 UTC, ajinabraham commented
@matandobr  The find was successful but the file read was failing in *nix. 


The json matches on the screenshot you shared looks good. Why is the view source failing in windows?
Is the path joined properly in windows https://github.com/matandobr/Mobile-Security-Framework-MobSF/blob/JAVA_TREEVIEW/StaticAnalyzer/views/android/view_source.py#L54

2020-10-24 20:59 UTC, matandobr commented
It is, but the reason it fails is that the search in the javascript is failing is because the separators in the HTML (due to the windows seperators) are \ and not /
So the search is returned great from the server but the select_nodes function is failing in the JS side,

2020-10-24 21:07 UTC, ajinabraham commented
@matandobr Tested ok Linux as well.

So where should we fix this? I was using pathlib so that it gives a consistent path format irrespective of OS. It can handle both windows and nix path. Does the issue needs a fix at JS side?

2020-10-24 21:15 UTC, matandobr commented
@ajinabraham 
I guess the right way to go is to change the tree_index_maker function within source_tree.py so it will use pathlib also... I'll try to fix it tomorrow

2020-10-24 21:17 UTC, ajinabraham commented
With that fix, this PR is good to merge 👍

2020-10-24 21:18 UTC, matandobr commented
great 👍

2020-10-31 02:08 UTC, ajinabraham approved these changes
LGTM 👍 Thanks for improving upon this.

2020-10-31 02:57 UTC, ajinabraham commented
Closing in favour of https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1572

2020-10-31 02:57 UTC, closed without merging