environment variable conflict
MobSF/Mobile-Security-Framework-MobSF pull request #1590
Opened 2020-11-13 02:29 UTC by ffucucuoglu

### Describe the Pull Request

```
MOBSF_API_KEY is not defined variable. It must MOBSF_API_KEY. Cause it to can't set api key from dockerfile.

```

### Checklist for PR

- [ ] Run MobSF unit tests and lint `tox -e lint,test`.
- [ ] Tested Working on Linux, Mac, Windows, and Docker
- [ ] Make sure build is passing on your PR. [![Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF.svg?branch=master)](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)

2020-11-13 18:13 UTC, ajinabraham requested changes
I do not understand why are you changing the `MOBSF_API_KEY` env var.  If you want to set the env var in docker set it when you run docker `-e MOBSF_API_KEY=your_api_key`

2020-11-13 21:57 UTC, ffucucuoglu commented
There are two environment variable for same purpose:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=MOBSF_SECRET_KEY
https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=MOBSF_API_KEY
Both of them used in only one file.
Merged in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/643
Therefore you cant set api key in dockerfile or docker-compose. Only way is setting both of them as environment variable.

2020-11-13 22:06 UTC, ajinabraham commented
Both serve a different purpose `MOBSF_API_KEY` environment variable allows you to set REST API key manually.
`MOBSF_SECRET_KEY` environment variable is used for Django secret feed. If `MOBSF_API_KEY` is set then the secret key environment variable or file is not used for REST API key generation.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/utils.py#L70


```bash
 docker run -it --rm -p 8000:8000 -e MOBSF_API_KEY=apikey123 opensecurity/mobile-security-framework-mobsf:latest
[INFO] 13/Nov/2020 22:05:53 - Mobile Security Framework v3.1.5 Beta
[INFO] 13/Nov/2020 22:05:53 -
API Key read from environment variable
REST API Key: apikey123
[INFO] 13/Nov/2020 22:05:53 - OS: Linux
....
```

2020-11-13 22:18 UTC, ffucucuoglu commented
> Both serve a different purpose `MOBSF_API_KEY` environment variable allows you to set REST API key manually.
> `MOBSF_SECRET_KEY` environment variable is used for Django secret feed. If `MOBSF_API_KEY` is set then the secret key environment variable or file is not used for REST API key generation.
> https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/utils.py#L70
> 
> ```shell
> docker run -it --rm -p 8000:8000 -e MOBSF_API_KEY=apikey123 opensecurity/mobile-security-framework-mobsf:latest
> [INFO] 13/Nov/2020 22:05:53 - Mobile Security Framework v3.1.5 Beta
> [INFO] 13/Nov/2020 22:05:53 -
> API Key read from environment variable
> REST API Key: apikey123
> [INFO] 13/Nov/2020 22:05:53 - OS: Linux
> ....
> ```

Ok thanks. I am closing.

2020-11-13 22:18 UTC, closed without merging

2020-11-14 15:03 UTC, masumiaban96 commented
Thank you
Best regards

On Sat, Nov 14, 2020, 1:27 AM fuat fucucuoglu <notifications@github.com>
wrote:

> There are two environment variable for same purpose:
>
> https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=MOBSF_SECRET_KEY
>
> https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=MOBSF_API_KEY
> Both of them used in only one file.
> Merged in #643
> <https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/643>
> Therefore you cant set api key in dockerfile or docker-compose. Only way
> is setting both of them as environment variable.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1590#issuecomment-727054820>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJLFK6W2UFKEJTQESO7B3J3SPWTVFANCNFSM4TUBJNGQ>
> .
>