Add Quark Engine as one of the static analyzers
MobSF/Mobile-Security-Framework-MobSF pull request #1761
Opened 2021-07-03 13:43 UTC by pulorsok

### Describe the Pull Request

This PR refers to [#1674](https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1674)

Hi @ajinabraham, sorry for taking so long to do this.
We (me, @18z, @krnick) have implemented some features for the integration:

#### 1. Add Quark Analysis Report

Add a button for Quark analysis at the nav menu.
Add Quark analysis report table that includes three columns:
1. **Potential malicious activity**: The description of potentially malicious activity detected by Quark.
2. **Source Code of Activity**: The class and method execute the APIs of potentially malicious activity.
3. **Confidence**: The number of confidence that the potentially malicious activity is practiced.

#### 2. Source code overview
Click on the link under the Source Code of Activity column, and it will open the exact .smali file and highlight the two APIs where the activities are executed.

Here is the demo:
![](https://i.imgur.com/L83yrws.gif)

### Checklist for PR

- [X] Run MobSF unit tests and lint `tox -e lint,test`
- [X] Tested Working on Linux, Mac, Windows, and Docker
- [X] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [X] Make sure tests are passing on your PR [![MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/workflows/MobSF%20tests/badge.svg?branch=master)](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

2021-07-04 18:46 UTC, ajinabraham commented
This is great @pulorsok
Thanks for this PR 💯 
I will do a review and get back to you.

2021-07-15 09:20 UTC, superpoussin22 commented
@pulorsok 
I have a repeating error when analyzing apks:
`[ERROR] 15/Jul/2021 08:03:36 - Find line number of method and apis
Traceback (most recent call last):
  File "/Users/vince/MyDev/Mobile-Security-Framework-MobSF/mobsf/MalwareAnalyzer/views/quark.py", line 127, in _get_line_numbers
    if not method_found:
UnboundLocalError: local variable 'method_found' referenced before assignment`

2021-07-15 09:31 UTC, superpoussin22 requested changes
see my proposal

2021-07-15 09:31 UTC, superpoussin22 commented on mobsf/MalwareAnalyzer/views/quark.py
> +
else:
    method_found = False

2021-07-18 03:13 UTC, ajinabraham approved these changes
Looking good, did some QA. 
Quark is using `git` to update rules. Testing it on our docker image.

2021-07-18 03:13 UTC, ajinabraham commented on mobsf/MalwareAnalyzer/views/quark.py
> +
Addressed this.

2021-07-18 07:20 UTC, superpoussin22 approved these changes
LGTM 👍

2021-07-18 07:51 UTC, merged